site_name: Ballerina.io
repo_url: https://github.com/ballerinalang/ballerina
site_description: Documentation for the Ballerina Programming Language
site_author: WSO2, Inc.
docs_dir: guides
copyright: 2018 WSO2, Inc.
theme: null
theme_dir: ballerina.io-guide_two-col-theme
